title: TV3
description: TV3
baseurl: ""
url: ""

markdown: kramdown
theme: null
plugins: []

collections:
  shows:
    output: true
    permalink: /s/:path/

defaults:
  - scope:
      path: ""
      type: "shows"
    values:
      layout: "show"
